version: '3'

volumes:
  mysql:
    driver: local

services:
  database:
    image: mysql:latest
    container_name: mysql-uow
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql:/var/lib/mysql